# Generated by Django 3.2.8 on 2021-10-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblogs',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
