# Generated by Django 3.2.8 on 2021-12-13 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('cluster_id', models.AutoField(db_column='Cluster_ID', primary_key=True, serialize=False)),
                ('cluster_name', models.TextField(db_column='Cluster_Name', unique=True)),
                ('depth', models.SmallIntegerField(db_column='Depth')),
                ('isScrapedCluster', models.BooleanField(default=False)),
                ('user_name', models.ForeignKey(db_column='User_Name', on_delete=django.db.models.deletion.DO_NOTHING, to='auth_app.authuser')),
            ],
            options={
                'db_table': 'Clusters',
                'managed': True,
                'unique_together': {('cluster_id', 'cluster_name')},
            },
        ),
        migrations.CreateModel(
            name='CrawlingStrategy',
            fields=[
                ('strategy_name', models.TextField(db_column='Strategy_Name', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Crawling_Strategy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UrlList',
            fields=[
                ('url_id', models.BigAutoField(db_column='URL_ID', primary_key=True, serialize=False)),
                ('url_name', models.TextField(db_column='URL_Name')),
                ('cluster', models.ForeignKey(db_column='Cluster_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='CreateClusters.clusters')),
            ],
            options={
                'db_table': 'URL_List',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClusterStrategy',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cluster', models.ForeignKey(db_column='Cluster_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='CreateClusters.clusters')),
                ('strategy', models.ForeignKey(db_column='Strategy', on_delete=django.db.models.deletion.DO_NOTHING, to='CreateClusters.crawlingstrategy')),
            ],
            options={
                'db_table': 'Cluster_Strategy',
                'managed': True,
            },
        ),
    ]
