# Generated by Django 3.2.8 on 2021-12-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('cluster_id', models.AutoField(db_column='Cluster_ID', primary_key=True, serialize=False)),
                ('cluster_name', models.TextField(db_column='Cluster_Name', unique=True)),
                ('depth', models.SmallIntegerField(db_column='Depth')),
                ('isScrapedCluster', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Clusters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClusterStrategy',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Cluster_Strategy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrawlingStrategy',
            fields=[
                ('strategy_name', models.TextField(db_column='Strategy_Name', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Crawling_Strategy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UrlList',
            fields=[
                ('url_id', models.BigAutoField(db_column='URL_ID', primary_key=True, serialize=False)),
                ('url_name', models.TextField(db_column='URL_Name')),
            ],
            options={
                'db_table': 'URL_List',
                'managed': False,
            },
        ),
    ]
