# Generated by Django 3.2.8 on 2021-11-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('cluster_id', models.AutoField(db_column='Cluster_ID', primary_key=True, serialize=False)),
                ('cluster_name', models.TextField(db_column='Cluster_Name')),
                ('depth', models.SmallIntegerField(db_column='Depth')),
            ],
            options={
                'db_table': 'Clusters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrawlingStrategy',
            fields=[
                ('strategy_name', models.TextField(db_column='Strategy_Name', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Crawling_Strategy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UrlList',
            fields=[
                ('url_id', models.BigAutoField(db_column='URL_ID', primary_key=True, serialize=False)),
                ('url_name', models.TextField(db_column='URL_Name')),
            ],
            options={
                'db_table': 'URL_List',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UrlStrategy',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'URL_Strategy',
                'managed': False,
            },
        ),
    ]
