# Generated by Django 3.2.8 on 2021-12-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateClusters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusters',
            name='isScrapedCluster',
            field=models.BooleanField(default=False),
        ),
    ]
