# Generated by Django 3.2.8 on 2021-11-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateClusters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterStrategy',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Cluster_Strategy',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UrlStrategy',
        ),
    ]
