# Generated by Django 3.2.8 on 2021-12-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateClusters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clusters',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='clusterstrategy',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='crawlingstrategy',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='urllist',
            options={'managed': False},
        ),
    ]
