# Generated by Django 3.2.8 on 2021-11-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateClusters', '0002_auto_20211124_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clusters',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='clusterstrategy',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='crawlingstrategy',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='urllist',
            options={'managed': True},
        ),
    ]
